// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jrwbdqfzvncgtfxgfbqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impyd2JkcWZ6dm5jZ3RmeGdmYnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4ODg3NjcsImV4cCI6MjA3MTQ2NDc2N30.G0qcHvVFHjQvHbXVYXUHEFPiOm7dBfin0KDMgUBhbIE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});